const {
  CD_WHITELIST_CONTRACT_ADDRESS,
  CD_NFT_CONTRACT_ADDRESS,
  CD_MARKETPLACE_CONTRACT_ADDRESS,
  CD_TOKEN_CONTRACT_ADDRESS,
} = require("../yourContracts.js");
// Address of the Whitelist Contract that you deployed
const WHITELIST_CONTRACT_ADDRESS = CD_WHITELIST_CONTRACT_ADDRESS;
// URL to extract Metadata for a Crypto Dev NFT
const METADATA_URL = "https://nft-collection-sneh1999.vercel.app/api/";
// Address of the NFT contract
const CRYPTO_DEVS_NFT_CONTRACT_ADDRESS = CD_NFT_CONTRACT_ADDRESS;
// Address of the Fake NFT Marketplace contract
const FAKE_NFT_MARKETPLACE_CONTRACT_ADDRESS = CD_MARKETPLACE_CONTRACT_ADDRESS;

const CRYPTO_DEV_TOKEN_CONTRACT_ADDRESS = CD_TOKEN_CONTRACT_ADDRESS;

module.exports = {
  WHITELIST_CONTRACT_ADDRESS,
  METADATA_URL,
  CRYPTO_DEVS_NFT_CONTRACT_ADDRESS,
  FAKE_NFT_MARKETPLACE_CONTRACT_ADDRESS,
  CRYPTO_DEV_TOKEN_CONTRACT_ADDRESS,
};
